#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

OS_ARCH_LINUX="amd64"

mkdir -p output/bin
if [ -n "$DRONE_TAG" ]; then
    TAG=$DRONE_TAG
fi

echo $TAG $DRONE_TAG

export buildDate=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

PKG_K8S_BASE="staging/src/k8s.io/component-base"
VERSIONFLAGS="
    -X ${PKG_K8S_BASE}/version.gitVersion=${TAG}
    -X ${PKG_K8S_BASE}/version.gitCommit=${COMMIT}
    -X ${PKG_K8S_BASE}/version.gitTreeState=clean
    -X ${PKG_K8S_BASE}/version.buildDate=${buildDate}
"

GOLDFLAGS=$VERSIONFLAGS

#cat <<EOF >"${KUBE_GIT_VERSION_FILE}"
#KUBE_GIT_COMMIT=${COMMIT}
#KUBE_GIT_TREE_STATE=clean
#KUBE_GIT_VERSION=v1.24.10
#KUBE_GIT_MAJOR=1
#KUBE_GIT_MINOR=24
#EOF


#cat ${KUBE_GIT_VERSION_FILE}


for ARCH in ${OS_ARCH_LINUX}; do
        echo Building kubelet-$ARCH
	
        build/run.sh make kubelet KUBE_BUILD_PLATFORMS=linux/$ARCH
	mv _output/dockerized/bin/linux/$ARCH/kubelet .
        ./kubelet --version 
        #tar -cvzf output/bin/kubelet-$TAG-$ARCH.tar.gz kubelet && rm kubelet
done

rm -rf _output/

echo Built ${TAG}
